### PR TITLE
Drop support for outdated Python versions

### PR DESCRIPTION
**Pull request by qarkai**
Also fix couple ruff warnings.

### CODE REVIEW

**Comment by cjrh** [comment]
Sorry for not commenting yet - I did see this PR, I just haven't had a good opportunity to look at it yet. I will get to it eventually promise 👍🏼

**Comment by cjrh** [comment]
After applying your changes, is the code still compatible with the versions in the [pyproject.toml](https://github.com/cjrh/aiorun/blob/master/pyproject.toml)?

**Comment by qarkai** [comment]
This PR removes quirks for Python <= 3.6.

**Review by cjrh — APPROVED** [review]
This looks good. Thank you so much 🙏🏼

**Pull request merged**
